id: P5F7784F7
initial_creation_type: input
source_metadata:
  Title: Śrāvakabhūmiḥ of Acarya Asanga
  Editor: Shukla, Karunesha
  Publisher: K. P. Jayaswal Research Institute
  Place of Publication: Patna
  Year: '1973'
  Prathamaṃ yogasthānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dvitīyaṃ yogasthānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Tṛtīyaṃ yogasthānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Caturthaṃ yogasthānam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:56:42.065948'
last_modified_at: '2022-03-08T16:56:42.065957'
